# Generated by Django 4.2 on 2024-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
