# Generated by Django 4.2 on 2024-08-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='monthly_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_price',
        ),
    ]
